json.extract! @beer, :id,
                    :name,
                    :rating,
                    :brewery_id,
                    :ibu,
                    :image_link,
                    :alc_percent,
                    :short_desc,
                    :long_desc,
                    :upc,
                    :category
